services:

  fhir-mcp-server:
    build: .
    image: docker.io/wso2/fhir-mcp-server:latest
    container_name: fhir-mcp-server
    environment:
      FHIR_SERVER_BASE_URL: https://demo.hopsiia.fr/fhir
      FHIR_SERVER_CLIENT_ID: ""
      FHIR_SERVER_CLIENT_SECRET: ""
      FHIR_SERVER_SCOPES: "fhirUser openid"
      FHIR_SERVER_DISABLE_AUTHORIZATION: True
      FHIR_MCP_HOST: 0.0.0.0
      FHIR_MCP_PORT: "8042"
      FHIR_MCP_REQUEST_TIMEOUT: "30"
    ports:
      - "8042:8042"
    networks:
      - mdb

networks:
  mdb:
    name: mdb